// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9I2arZX-BCc6gKSFWV-Gp9P7KFLiDLdw',
    appId: '1:407659083403:web:f105dd3ea6b9d7ec8b068e',
    messagingSenderId: '407659083403',
    projectId: 'inventory-manger-2hand-matrix',
    authDomain: 'inventory-manger-2hand-matrix.firebaseapp.com',
    storageBucket: 'inventory-manger-2hand-matrix.appspot.com',
    measurementId: 'G-TFTXYSEG3S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYzijKCf02HE1JL0_31YewuOK9iI6TWQk',
    appId: '1:407659083403:android:93b2753ebaec11728b068e',
    messagingSenderId: '407659083403',
    projectId: 'inventory-manger-2hand-matrix',
    storageBucket: 'inventory-manger-2hand-matrix.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbwXbq6k8BjTAa3ewaDQubw6J-DPLouwk',
    appId: '1:407659083403:ios:640c044ea81092998b068e',
    messagingSenderId: '407659083403',
    projectId: 'inventory-manger-2hand-matrix',
    storageBucket: 'inventory-manger-2hand-matrix.appspot.com',
    iosClientId: '407659083403-jhb8v8acijc79pkn1badok9jvgkhj2rr.apps.googleusercontent.com',
    iosBundleId: 'drmatrix.flutter.inventoryManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbwXbq6k8BjTAa3ewaDQubw6J-DPLouwk',
    appId: '1:407659083403:ios:640c044ea81092998b068e',
    messagingSenderId: '407659083403',
    projectId: 'inventory-manger-2hand-matrix',
    storageBucket: 'inventory-manger-2hand-matrix.appspot.com',
    iosClientId: '407659083403-jhb8v8acijc79pkn1badok9jvgkhj2rr.apps.googleusercontent.com',
    iosBundleId: 'drmatrix.flutter.inventoryManager',
  );
}
